root: true #ルートディレクトリの設定ファイルに記述
# # ts-eslintの共有設定にて定義済み
# parser: "@typescript-eslint/parser"
# parserOptions:
#   project: ./tsconfig.json
#   sourceType: "module"
# plugins:
#   - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/eslint-recommended #plugin:@typescript-eslint/recommendedにて定義済み
  - prettier
env:
  browser: true
rules:
  no-console: 1
